const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  fio: {
    getTags: () => ipcRenderer.invoke('fio:getTags'),
    getValues: () => ipcRenderer.invoke('fio:getValues'),
    setValues: (body) => ipcRenderer.invoke('fio:setValues', body),
    setValuesByName: (body) => ipcRenderer.invoke('fio:setValuesByName', body),
    forceValues: (body) => ipcRenderer.invoke('fio:forceValues', body),
    releaseValues: (body) => ipcRenderer.invoke('fio:releaseValues', body),
    connect: (url) => ipcRenderer.invoke('fio:connect', url),
    disconnect: () => ipcRenderer.invoke('fio:disconnect'),
    onTags: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('factoryio-tags', h); return () => ipcRenderer.removeListener('factoryio-tags', h); },
    onStatus: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('factoryio-status', h); return () => ipcRenderer.removeListener('factoryio-status', h); },
  },
  opcua: {
    connect: (url) => ipcRenderer.invoke('opcua:connect', url),
    disconnect: () => ipcRenderer.invoke('opcua:disconnect'),
    getTags: () => ipcRenderer.invoke('opcua:getTags'),
    read: (nodeId) => ipcRenderer.invoke('opcua:read', nodeId),
    write: (nodeId, value, dataType) => ipcRenderer.invoke('opcua:write', nodeId, value, dataType),
    status: () => ipcRenderer.invoke('opcua:status'),
  },
  modbus: {
    connect: (config) => ipcRenderer.invoke('modbus:connect', config),
    disconnect: () => ipcRenderer.invoke('modbus:disconnect'),
    getTags: () => ipcRenderer.invoke('modbus:getTags'),
    writeRegister: (address, value) => ipcRenderer.invoke('modbus:writeRegister', address, value),
    writeCoil: (address, value) => ipcRenderer.invoke('modbus:writeCoil', address, value),
    status: () => ipcRenderer.invoke('modbus:status'),
    onStatus: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('modbus-status', h); return () => ipcRenderer.removeListener('modbus-status', h); },
  },
  mqtt: {
    connect: (url) => ipcRenderer.invoke('mqtt:connect', url),
    disconnect: () => ipcRenderer.invoke('mqtt:disconnect'),
    publish: (topic, payload) => ipcRenderer.invoke('mqtt:publish', topic, payload),
    subscribe: (topic) => ipcRenderer.invoke('mqtt:subscribe', topic),
    status: () => ipcRenderer.invoke('mqtt:status'),
    onMessage: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('mqtt-message', h); return () => ipcRenderer.removeListener('mqtt-message', h); },
    onStatus: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('mqtt-status', h); return () => ipcRenderer.removeListener('mqtt-status', h); },
  },
  influx: {
    connect: (config) => ipcRenderer.invoke('influx:connect', config),
    disconnect: () => ipcRenderer.invoke('influx:disconnect'),
    query: (fluxQuery) => ipcRenderer.invoke('influx:query', fluxQuery),
    status: () => ipcRenderer.invoke('influx:status'),
    setup: (config) => ipcRenderer.invoke('influx:setup', config),
    onStatus: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('influx-status', h); return () => ipcRenderer.removeListener('influx-status', h); },
  },
  store: {
    get: (key) => ipcRenderer.invoke('store:get', key),
    set: (key, value) => ipcRenderer.invoke('store:set', key, value),
    delete: (key) => ipcRenderer.invoke('store:delete', key),
    getAll: () => ipcRenderer.invoke('store:getAll'),
  },
  alarms: {
    getAll: () => ipcRenderer.invoke('alarms:getAll'),
    acknowledge: (id) => ipcRenderer.invoke('alarms:acknowledge', id),
    clear: (id) => ipcRenderer.invoke('alarms:clear', id),
    clearAll: () => ipcRenderer.invoke('alarms:clearAll'),
    setThresholds: (thresholds) => ipcRenderer.invoke('alarms:setThresholds', thresholds),
    getThresholds: () => ipcRenderer.invoke('alarms:getThresholds'),
    onNew: (cb) => { const h = (_, d) => cb(d); ipcRenderer.on('new-alarms', h); return () => ipcRenderer.removeListener('new-alarms', h); },
  },
  services: {
    status: () => ipcRenderer.invoke('services:status'),
    autostart: () => ipcRenderer.invoke('services:autostart'),
    getConfig: () => ipcRenderer.invoke('services:getConfig'),
    setConfig: (config) => ipcRenderer.invoke('services:setConfig', config),
  },
  simulation: {
    start: (interval) => ipcRenderer.invoke('simulation:start', interval),
    stop: () => ipcRenderer.invoke('simulation:stop'),
    status: () => ipcRenderer.invoke('simulation:status'),
    getTags: () => ipcRenderer.invoke('simulation:getTags'),
    getHistory: (name, minutes) => ipcRenderer.invoke('simulation:getHistory', name, minutes),
    getPredictions: () => ipcRenderer.invoke('simulation:getPredictions'),
    getOEE: () => ipcRenderer.invoke('simulation:getOEE'),
    setTag: (name, value) => ipcRenderer.invoke('simulation:setTag', name, value),
    injectAnomaly: (name, type, duration) => ipcRenderer.invoke('simulation:injectAnomaly', name, type, duration),
    setMachineStatus: (id, status) => ipcRenderer.invoke('simulation:setMachineStatus', id, status),
    getMachines: () => ipcRenderer.invoke('simulation:getMachines'),
    getProductionState: () => ipcRenderer.invoke('simulation:getProductionState'),
  },
  gmao: {
    getWorkOrders: () => ipcRenderer.invoke('gmao:getWorkOrders'),
    saveWorkOrder: (wo) => ipcRenderer.invoke('gmao:saveWorkOrder', wo),
    deleteWorkOrder: (id) => ipcRenderer.invoke('gmao:deleteWorkOrder', id),
    getAssets: () => ipcRenderer.invoke('gmao:getAssets'),
    saveAsset: (asset) => ipcRenderer.invoke('gmao:saveAsset', asset),
  },
  mes: {
    getProductionOrders: () => ipcRenderer.invoke('mes:getProductionOrders'),
    saveProductionOrder: (po) => ipcRenderer.invoke('mes:saveProductionOrder', po),
    getOEE: () => ipcRenderer.invoke('mes:getOEE'),
    saveOEE: (oee) => ipcRenderer.invoke('mes:saveOEE', oee),
  },
});